{% set name = "csdms-stack" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  entry_points: []
  number: 3

requirements:
  run:
  - pymt
  - cca-tools
  - csdms-child
  - csdms-sedflux-3d
  - csdms-hydrotrend
  - csdms-permamodel
  - csdms-brake
  - csdms-pydeltarcm

extra:
  copy_test_source_files: true
  final: true
